AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a JuypterLabs server

Parameters:
  InstanceType:
    Description: Intel Xeon 4 Scalable Processor
    Type: String
    Default: m7i.4xlarge
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The VPC ID where the EC2 instance will be launched.

Resources:
  SSMforEC2Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'ec2.amazonaws.com'
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'
      Policies:
        - PolicyName: 'ReadHFApiTokenParameter'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'ssm:GetParameter'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/huggingface/api_token'
      RoleName: 'SSMforEC2'

  SSMforEC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: 'SSMforEC2InstanceProfile'
      Roles:
        - !Ref 'SSMforEC2Role'
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: 'Allow HTTP traffic from the internet'
      VpcId: !Ref 'VpcId'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8888
          ToPort: 8888
          CidrIp: '0.0.0.0/0'

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMIID]
      IamInstanceProfile: !Ref 'SSMforEC2InstanceProfile'
      SecurityGroupIds:
        - !Ref 'EC2SecurityGroup'
      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            VolumeSize: 80
            VolumeType: gp3
Mappings:
  RegionMap:
    us-east-1:
      AMIID: 'ami-0866a3c8686eaeeba'

Outputs:
  EC2InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt 'Ec2Instance.PublicIp'